apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-couchdb.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: couchdb
      protocol: TCP
      name: couchdb
  selector:
    app: {{ include "hlf-couchdb.name" . }}
    release: {{ .Release.Name }}
